/*
===============================================================================
Customer Report
===============================================================================
Purpose:
    - This report consolidates key customer metrics and behaviors

Highlights:
    1. Gathers essential fields such as names, ages, and transaction details.

	2. Segments customers into categories (VIP, Regular, New) and age groups.

    3. Aggregates customer-level metrics:
	   - total orders
	   - total sales
	   - total quantity purchased
	   - total products
	   - lifespan (in months)
    4. Calculates valuable KPIs:
	    - recency (months since last order)
		- average order value (per customer)
		- average monthly spend (per customer)

	5. Segments customers by age:
	    - Under 20, 20-29, 30-39, 40-49, 50 and above

	6. Segments customers by customer segment based on lifespan and sales:
		VIP → lifespan ≥ 12 months and total sales > 5000
		Regular → lifespan ≥ 12 months and total sales ≤ 5000
		New → lifespan < 12 months

- At last ,Create a view from this query so it can be reused for reports.
===============================================================================
*/

-- ============================================================
-- Drop the view if it already exists
-- ============================================================
IF OBJECT_ID('gold._V_customer_report', 'V') IS NOT NULL
    DROP VIEW gold._V_customer_report;
GO


-- ============================================================
-- Create the customer report view
-- This view combines sales and customer data
-- and produces customer-level analytics.
-- ============================================================
CREATE VIEW gold._V_customer_report AS


-- ============================================================
-- CTE 1: initial_data
-- Brings customer and sales information together.
-- ============================================================
WITH initial_data AS
(
    SELECT
        C.customer_key,
        C.customer_number,
        C.first_name, 
        C.last_name,
        
        -- Calculate the customer's age based on birthdate
        DATEDIFF(YEAR, C.birthdate, GETDATE()) AS customer_age,

        F.order_number,
        F.quantity,
        F.product_key,
        F.sales_amount,
        F.order_date
    FROM gold.fact_sales AS F
    LEFT JOIN gold.dim_customers AS C
        ON F.customer_key = C.customer_key
),


-- ============================================================
-- CTE 2: customer_level_aggregation
-- Aggregates all orders for each customer.
-- Produces total orders, total sales, last order date, etc.
-- ============================================================
customer_level_aggregation AS
(
    SELECT
        customer_key,
        customer_number,
        first_name,
        last_name,
        customer_age,

        -- How many unique orders?
        COUNT(DISTINCT order_number) AS total_orders,

        -- Total quantity purchased by the customer
        SUM(quantity) AS total_quantity,

        -- How many different products the customer bought?
        COUNT(DISTINCT product_key) AS total_products,

        -- Total revenue generated by the customer
        SUM(sales_amount) AS sales_amount,

        -- Most recent purchase date
        MAX(order_date) AS last_order_date,

        -- Customer lifespan in months
        -- (difference between first and last order)
        DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS customer_lifespan_months
    FROM initial_data
    GROUP BY
        customer_key,
        customer_number,
        first_name,
        last_name,
        customer_age
)


-- ============================================================
-- Final SELECT: Generates customer-level report
-- Includes segmentation, recency, and calculated metrics.
-- ============================================================
SELECT
    customer_key,
    customer_number,

    -- Combine first and last name
    CONCAT(first_name, ' ', last_name) AS customer_name,

    customer_age,

    -- Age segmentation
    CASE
        WHEN customer_age IS NULL               THEN 'n/a'
        WHEN customer_age BETWEEN 0  AND 30     THEN '0 to 30 years'
        WHEN customer_age BETWEEN 31 AND 60     THEN '31 to 60 years'
        WHEN customer_age BETWEEN 61 AND 90     THEN '61 to 90 years'
        ELSE 'Above 90 years'
    END AS customer_age_segmentation,

    -- Customer type segmentation
    CASE
        WHEN customer_lifespan_months IS NULL                        THEN 'n/a'
        WHEN customer_lifespan_months >= 12 AND sales_amount > 5000  THEN 'vip'
        WHEN customer_lifespan_months >= 12 AND sales_amount <= 5000 THEN 'regular'
        ELSE 'new'
    END AS customer_segment,

    last_order_date,

    -- Recency = how long since last order
    DATEDIFF(YEAR, last_order_date, GETDATE()) AS recency_years,

    total_products,
    total_orders,
    total_quantity,
    sales_amount,
    customer_lifespan_months,

    -- AOV (Average Order Value) = total sales / total orders
    ISNULL(sales_amount / NULLIF(total_orders, 0), 0) AS average_order_value,

    -- AMS (Average Monthly Spend) = total sales / customer lifespan
    ISNULL(sales_amount / NULLIF(customer_lifespan_months, 0), 0) AS average_monthly_spend
FROM customer_level_aggregation;
GO




-- CHECK THE VIEW ,
SELECT *
FROM gold._V_customer_report 
ORDER BY customer_key ;
GO


