/*
================================================================================
Product Report View
================================================================================
Purpose:
    This view provides a consolidated, product-level summary that helps business
    users understand how each product is performing over time.

What this report answers:
    - Which products generate the most revenue?
    - How frequently products are ordered and by how many customers?
    - How long each product has been active in sales history?
    - How recently each product was sold?
================================================================================
*/

IF OBJECT_ID('gold._V_product_report', 'V') IS NOT NULL
    DROP VIEW gold._V_product_report;
GO

CREATE VIEW gold._V_product_report AS

/*
-------------------------------------------------------------------------------
Step 1: Prepare base sales data
-------------------------------------------------------------------------------
This step combines sales transactions with product details so that each sale
contains both commercial and descriptive product information.
*/
WITH initial_data AS
(
    SELECT
        P.product_key,
        P.product_name,
        P.category,
        P.subcategory,
        P.cost,
        F.order_number,
        F.customer_key,
        F.quantity,
        F.sales_amount,
        F.order_date
    FROM gold.fact_sales AS F
    LEFT JOIN gold.dim_products AS P
        ON F.product_key = P.product_key
    WHERE F.order_date IS NOT NULL
),

/*
-------------------------------------------------------------------------------
Step 2: Aggregate data at product level
-------------------------------------------------------------------------------
This step summarizes all transactions to create one row per product, capturing
customer reach, order behavior, revenue, and product activity period.
*/
product_initial_aggregation AS
(
    SELECT
        product_key,
        product_name,
        category,
        subcategory,
        cost,

        -- Number of unique customers who purchased the product
        COUNT(DISTINCT customer_key) AS total_customers,

        -- Number of distinct orders placed for the product
        COUNT(DISTINCT order_number) AS total_orders,

        -- Total units sold
        SUM(quantity) AS total_quantity,

        -- Total revenue generated by the product
        SUM(sales_amount) AS total_sales_amount,

        -- Average revenue per transaction (not per unit)
        AVG(sales_amount) AS avg_sales_amount,

        -- Average selling price per unit
        ROUND(
            AVG(CAST(sales_amount AS FLOAT) / NULLIF(quantity, 0)),
            1
        ) AS avg_selling_price,

        -- Number of months the product has been active in sales data
        DATEDIFF(
            MONTH,
            MIN(order_date),
            MAX(order_date)
        ) AS product_lifespan_months,

        -- Most recent date the product was sold
        MAX(order_date) AS last_sale_date
    FROM initial_data
    GROUP BY
        product_key,
        product_name,
        category,
        subcategory,
        cost
)

/*
-------------------------------------------------------------------------------
Step 3: Final business metrics and segmentation
-------------------------------------------------------------------------------
This step derives business-friendly KPIs and classifies products based on
revenue contribution.
*/
SELECT
    product_key,
    product_name,
    category,
    subcategory,
    cost,

    last_sale_date,

    -- Time since the product was last sold
    DATEDIFF(YEAR, last_sale_date, GETDATE()) AS recency_in_year,

    -- Revenue-based performance classification
    CASE
        WHEN total_sales_amount > 50000 THEN 'high performer'
        WHEN total_sales_amount >= 10000 THEN 'mid performer'
        ELSE 'low performer'
    END AS product_segment_based_on_total_sales,

    product_lifespan_months,
    total_orders,
    total_sales_amount,
    total_quantity,
    total_customers,
    avg_selling_price,

    -- Average revenue earned per order
    ROUND(
        CAST(total_sales_amount AS FLOAT) / NULLIF(total_orders, 0),
        1
    ) AS avg_order_revenue,

    -- Average revenue generated per month during the product's active period
    ROUND(
        CAST(total_sales_amount AS FLOAT) / NULLIF(product_lifespan_months, 0),
        1
    ) AS avg_monthly_revenue
FROM product_initial_aggregation;
GO

-- Validate the view output
SELECT *
FROM gold._V_product_report;
